### PR TITLE
adding more layers

### PR DESCRIPTION
**Pull request by dalekunce**
@hallahan can you merge this in please and push to production.

### CODE REVIEW

**Comment by hallahan** [comment]
Ok, I'm able to get your changes to work locally. Merging.

**Comment by dalekunce** [comment]
@danielduhh can you please deploy this to production as part of the existing work.

**Comment by danielduhh** [comment]
Yeah. It looks like GeoForce is running off the "prod" branch. Could you send a pull request to that? @dalekunce

**Comment by dalekunce** [comment]
@danielduhh master branch looks to be ahead of the prod branch. Can you bring everything to the same point and deploy the master (most recent version).

**Comment by danielduhh** [comment]
@dalekunce deployed to production

**Comment by dalekunce** [comment]
@danielduhh thanks

**Pull request merged**
